#Time,Open,Max,Min,Close,Volume
instrument: 'XAUUSD'
#features_idx: [1,2,3]
features_idx: [1]
instrument_idx: 1
# Model variables
c: 1
learning_rate: 0.001
epochs: 100
n_layers: [30] #FIXME Has to be the same number in each layer!!
window_size: 21
n_actions: 500
last_n_values: 1000